name: Feature Request
description: 새로운 기능을 제안하거나 기존 기능을 개선합니다.
labels: ["enhancement"]
body:
  - type: textarea
    id: background
    attributes:
      label: 제안 배경 및 필요성
      description: 해당 기능이 왜 필요한지, 어떤 문제를 해결하고자 하는지 기술해주세요.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: 상세 구현 방안
      description: 생각하신 구체적인 기능 작동 방식이나 구현 아이디어를 적어주세요.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 고려해본 대안
      description: 제안한 방법 외에 검토했거나 고려할 수 있는 다른 대안이 있다면 설명해주세요.
    validations:
      required: true